#!/bin/bash
#SBATCH --job-name="PostProcess_example"
#SBATCH -p parallel-16
#SBATCH -n 8
#SBATCH -t 100:00:00
#SBATCH --mem-per-cpu=1G

EXEC=lmp
if lscpu | grep -q "avx512"; then
    echo "AVX512 is available on node $(hostname)"
    AVX=avx512
# else check avx2
elif lscpu | grep -q "avx2"; then
    echo "AVX2 is available on node $(hostname)"
    AVX=avx2
# else avx
elif lscpu | grep -q "avx"; then
    echo "AVX is available on node $(hostname)"
    AVX=avx
else
    echo "No suitable AVX instruction set found on node $(hostname), exiting."
    exit 1
fi

srun "${EXEC}_${AVX}" -i simulation.in -sf omp -pk omp 1
